packages:
  - 'apps/*'
  - 'examples/*'
  - 'services/*'
  - 'packages/*'

nodeVersion: 24.14.1
engineStrict: true
pmOnFail: error

allowBuilds:
  '@bufbuild/buf': true
  esbuild: true
  workerd: true

catalog:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  '@bufbuild/buf': 1.72.0
  '@bufbuild/protobuf': 2.13.0
  '@bufbuild/protoc-gen-es': 2.13.0
  '@vitejs/plugin-react': 6.0.5
  hls.js: 1.7.0-rc.3
  oxfmt: 0.59.0
  oxlint: 1.74.0
  react: 19.2.8
  react-dom: 19.2.8
  tsx: 4.23.5
  typescript: 7.0.2
  vite: 8.2.0
  wrangler: 4.118.0

disallowWorkspaceCycles: true
saveWorkspaceProtocol: rolling
strictPeerDependencies: true
