[package]
name = "storya-http-proxy"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
